config/routes.rb
Auth::Application.routes.draw do

  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"

  resources :foods
  match "/operations" => "operations#create", :via => :post

  resources :identities

  resources :users

  match "/dashboard", to: "dashboard#index", :as => "dashboard"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include ApplicationHelper

  def index
    @identity = Identity.find(current_user.uid) if current_user
    @foods = Food.all
    @view_name = "Dashboard"
    @operation = Operation.new
    @operations = Operation.limit(15).all(:order => :date.desc)

    @start_date = 1.week.ago.utc

    Struct.new("TopUser", :name, :email, :gravatar_img, :value)

    top_eater = Operation.collection.group(['user_id'],
                                           {:value => {"$lt" => 1}},
                                           {'sum' => 0},
                                           "function(doc, prev) { prev.sum += doc.value}").sort { |x, y| x["sum"] <=> y["sum"] }.first()
    if top_eater
      top_eater_identity = Identity.find(User.find(top_eater["user_id"]).uid)
      @top_eater_user = Struct::TopUser.new(top_eater_identity.name,
                                            top_eater_identity.email,
                                            gravatar(top_eater_identity.email, :size => 40).html_safe,
                                            top_eater["sum"])
    end

    top_contributor = Operation.collection.group(['user_id'],
                                                 {:value => {"$gte" => 1}},
                                                 {'sum' => 0},
                                                 "function(doc, prev) { prev.sum += doc.value}").sort { |x, y| y["sum"] <=> x["sum"] }.first()
    if top_contributor
      top_contributor_identity = Identity.find(User.find(top_contributor["user_id"]).uid)
      @top_contributor_user = Struct::TopUser.new(top_contributor_identity.name,
                                                  top_contributor_identity.email,
                                                  gravatar(top_contributor_identity.email, :size => 40).html_safe,
                                                  top_contributor["sum"])
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="span3">
    <h4>Food available</h4>
    <br/>
    <table>
      <% @foods.each do |f| %>
        <tr>
          <td>
            <% if f.remaining %>
              <% if f.remaining > 10 %>
                <% class_span = "label-info" %>
              <% elsif f.remaining > 5 %>
                <% class_span = "label-success" %>
              <% elsif f.remaining > 0 %>
                <% class_span = "label-warning" %>
              <% else %>
                <% class_span = "label-important" %>
              <% end %>
              <%= content_tag :span, :class => "label " + class_span, :style => "vertical-align: text-top;" do %>
                <%= f.remaining %>
              <% end %>
            <% end %>
          </td>
          <td>
            <%= link_to food_path(f.id) do %>
              <%= f.name %>
            <% end %>
          </td>
          <td>
            <%= link_to "#shareFood_#{f.id}", :class => "btn btn-mini", :data => {:toggle => "modal"} do %>
              <i class="icon-star"></i> Share
            <% end %>
            <%= content_tag :div, :id => "shareFood_#{f.id}", :class => "modal hide fade", :style => "display: none; " do %>
              <div class="modal-header">
                <a class="close" data-dismiss="modal">×</a>

                <h3>Share <%= f.name %> !</h3>
              </div>
              <div class="modal-body">
                <%= form_for(@operation) do |o| %>
                  How generous are you ? <%= o.text_field :value, :class => "input-small", :type => "number", :min => "1" %>
                  <%= o.hidden_field :user_id, {:value => current_user.id} %>
                  <%= o.hidden_field :food_id, {:value => f.id} %>
                  </div>
                  <div class="modal-footer">
                    <a href="#" class="btn" data-dismiss="modal">Close</a>
                    <%= o.submit "Save", :type => "submit", :class => "btn btn-primary" %>
                  </div>
                <% end %>
            <% end %>
            <%= form_for(@operation, :html => {:style => "display : inline-block; margin : 0; "}) do |o| %>
              <%= o.hidden_field :value, {:value => -1} %>
              <%= o.hidden_field :user_id, {:value => current_user.id} %>
              <%= o.hidden_field :food_id, {:value => f.id} %>
              <%= o.submit "Eat !", :type => "submit", :class => "btn btn-danger btn-mini" do %>
                <i class="icon-chevron-right icon-white"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
    <br/>
    <%= link_to new_food_path, :class => "btn btn-primary btn-mini" do %>
      <i class="icon-plus icon-white"></i> Add new food
    <% end %>
  </div>
  <div class="span6">
    <h3>Latest operations</h3>
    <table class="table table-condensed">
      <% @operations.each do |o| %>
        <tr>
          <td>
            <% if o.value > 0 %>
              <span class="label label-inverse" style="vertical-align: text-top;"> <%= o.value %></span>
            <% else %>
              <span class="label label-default" style="vertical-align: text-top;"> <%= o.value %></span>
            <% end %>
          </td>
          <td>
            <%= o.food.name if o.food %>
          </td>
          <td>
            <strong><%= o.user.name if o.user %></strong>
          </td>
          <td>
            <%= time_ago_in_words(o.date) + " ago" if o.date %>
          </td>
      <% end %>
    </table>

  </div>
  <div class="span3">
    <div>
      <% if @top_eater_user %>
        <h4>Top eater</h4>
        <table style="margin-bottom: 5px">
          <tr>
            <td>
              <%= @top_eater_user.gravatar_img %>
            </td>
            <td>
              <%= @top_eater_user.name %>
              <br/>
              <span class="label label-important"><%= @top_eater_user.value %></span>
            </td>
          </tr>
        </table>
        <div class="btn-group" data-toggle="buttons-radio">
          <button class="btn week-btn" style="padding: 2px 4px 2px 4px">Week</button>
          <button class="btn" style="padding: 2px 4px 2px 4px">Month</button>
          <button class="btn" style="padding: 2px 4px 2px 4px">All time</button>
        </div>
      <% end %>
    </div>
    <br/>
    <br/>

    <div>
      <% if @top_contributor_user %>
        <h4>Top contributor</h4>
        <table style="margin-bottom: 5px">
          <tr>
            <td>
              <%= @top_contributor_user.gravatar_img %>
            </td>
            <td>
              <%= @top_contributor_user.name %>
              <br/>
              <span class="label label-success"><%= @top_contributor_user.value %></span>
            </td>
          </tr>
        </table>
        <div class="btn-group" data-toggle="buttons-radio">
          <button class="btn week-btn" style="padding: 2px 4px 2px 4px">Week</button>
          <button class="btn week-month-contributor" style="padding: 2px 4px 2px 4px">Month</button>
          <button class="btn" style="padding: 2px 4px 2px 4px">All time</button>
        </div>
      <% end %>
    </div>
    <script>
      $('.week-btn').button('toggle')
    </script>
  </div>
</div>