config/routes.rb
Auth::Application.routes.draw do

  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"

  resources :foods
  match "/operations" => "operations#create", :via => :post

  resources :identities

  resources :users

  match "/dashboard", to: "dashboard#index", :as => "dashboard"
end

app/models/food.rb
class Food
  include MongoMapper::Document

  key :name, String
  key :creator_uid, String
  key :remaining, Integer

  many :operations

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])
    @view_name = @food.name
    @operations = Operation.limit(5).all(:food_id => params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    @view_name = "New food"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])
    @food.remaining = 0

    respond_to do |format|
      if @food.save
        format.html { redirect_to dashboard_url, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food, :html => {:class => "well form-inline"}) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% @food.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <%= f.text_field :name, :placeholder => "Name" %>
  <%= f.submit "Create food", :class => "btn-primary" %>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @foods.each do |food| %>
    <tr>
      <td><%= link_to 'Show', food %></td>
      <td><%= link_to 'Edit', edit_food_path(food) %></td>
      <td><%= link_to 'Destroy', food, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', dashboard_path, :class => "btn" %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <h4>Current :
    <% if @food.remaining %>
      <% if @food.remaining > 10 %>
        <% class_span = "label-info" %>
      <% elsif @food.remaining > 5 %>
        <% class_span = "label-success" %>
      <% elsif @food.remaining > 0 %>
        <% class_span = "label-warning" %>
      <% else %>
        <% class_span = "label-important" %>
      <% end %>
      <%= content_tag :span, :class => "label " + class_span, :style => "vertical-align: text-top;" do %>
        <%= @food.remaining %>
      <% end %>
    <% end %>
  </h4>
  <br/>
  <table class="table table-condensed">
    <% @operations.each do |o| %>
      <tr>
        <td>
          <% if o.value > 0 %>
            <span class="label label-inverse" style="vertical-align: text-top;"> <%= o.value %></span>
          <% else %>
            <span class="label label-default" style="vertical-align: text-top;"> <%= o.value %></span>
          <% end %>
        </td>
        <td>
          <strong><%= o.user.name if o.user %></strong>
        </td>
        <td>
          <%= time_ago_in_words(o.date) + " ago" if o.date %>
        </td>
    <% end %>
  </table>
</div>
<%= link_to 'Back', dashboard_path, :class => "btn" %>