config/routes.rb
Auth::Application.routes.draw do

  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"

  resources :foods
  match "/operations" => "operations#create", :via => :post

  resources :identities

  resources :users

  match "/dashboard", to: "dashboard#index", :as => "dashboard"
end

app/models/operation.rb
class Operation
  include MongoMapper::Document

  attr_accessor :user_id
  @user_id

  attr_accessor :food_id
  @food_id

  key :value, Integer
  key :date, Time

  belongs_to :user
  belongs_to :food
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @operations }
    end
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @operation = Operation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @operation }
    end
  end

  # GET /operations/new
  # GET /operations/new.json
  def new
    @operation = Operation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @operation }
    end
  end

  # GET /operations/1/edit
  def edit
    @operation = Operation.find(params[:id])
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(params[:operation])

    user = User.find(@operation.user_id)
    @operation.user = user

    food = Food.find(@operation.food_id)
    if food.remaining.nil?
      food.remaining = 0
    end

    food.remaining = food.remaining + @operation.value
    if food.remaining < 0
      respond_to do |format|
        format.html { redirect_to dashboard_url, :flash => {:error => 'You can\'t eat anymore!'} }
        format.json { render text: 'You can\'t anymore !', status: :unprocessable_entity }
      end
    else
      food.save
      @operation.food = food

      @operation.date = Time.zone.now.to_datetime

      respond_to do |format|
        if @operation.save
          format.html { redirect_to dashboard_url, notice: 'Yummy!' }
          format.json { render json: @operation, status: :created, location: @operation }
        else
          format.html { redirect_to dashboard_url, notice: 'Failed to create operation !' }
          format.json { render json: @operation.errors, status: :unprocessable_entity }
        end
      end
    end

  end


# PUT /operations/1
# PUT /operations/1.json
  def update
    @operation = Operation.find(params[:id])

    respond_to do |format|
      if @operation.update_attributes(params[:operation])
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /operations/1
# DELETE /operations/1.json
  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    respond_to do |format|
      format.html { redirect_to operations_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% @operation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %>
    <br/>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing operation</h1>

<%= render 'form' %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<h1>Listing operations</h1>

<table>
  <tr>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @operations.each do |operation| %>
    <tr>
      <td><%= operation.value %></td>
      <td><%= link_to 'Show', operation %></td>
      <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
      <td><%= link_to 'Destroy', operation, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New operation</h1>

<%= render 'form' %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @operation.value %>
</p>


<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>